Repository ghc-proposals/ghc-proposals, pull requests merged in 2019-11, with the labels that each got.

#254 Scale back "Function Result Type Signatures" to keep pattern sigs as-is
  proposals/0228-function-result-sigs.rst
Labels: Pending shepherd recommendation

#290 Fix module exports in examples
  proposals/0160-no-toplevel-field-selectors.rst
Labels: Non-proposal

#299 Explain how to amend a proposal
  README.rst
Labels: Non-proposal

#300 Correct the spelling of amendment
  README.rst
Labels: Non-proposal

#293 Tweaks to #229 (under review)
  proposals/0229-whitespace-bang-patterns.rst
Labels: Pending committee review
