Repository ghc-proposals/ghc-proposals, pull requests merged in 2020-05, with the labels that each got.

#282 RecordDotSyntax language extension proposal
  proposals/0000-record-dot-syntax.md
Labels: Pending shepherd recommendation

#285 `-XNoImplicitForAll`, `-XNoPatternSignatureBinds`
  proposals/0000-no-implicit-binds.rst
Labels: Accepted

#329 Typo foral
  proposals/0285-no-implicit-binds.rst
Labels: Non-proposal

#320 Ignore class defaults for associated type instances in instances that occur in backpack and hs-boot files (under review)
  proposals/0000-signature-instances.md
Labels: Pending committee review

#216 Local do
  proposals/0000-local-do.rst
Labels: Accepted

#195 Make Q (TExp a) into a newtype
  proposals/0000-code-texp.rst
Labels: Accepted

#339 Rename 229 and change handling of prefix @
  proposals/0229-whitespace-bang-patterns.rst
Labels: Non-proposal
