Repository ghc-proposals/ghc-proposals, pull requests merged in 2021-05, with the labels that each got.

#419 Rewrite/extend 2.1.1 syntax note
  proposals/0282-record-dot-syntax.rst
Labels: Non-proposal

#371 Export ~ from Data.Type.Equality (under review)
  proposals/0000-non-magical-eq.md
Labels: Pending committee review

#415 OPAQUE pragma (under review)
  proposals/0000-opaque-pragma.md
Labels: Pending shepherd recommendation

#378 Support the design for dependent types (under review)
  proposals/0000-dependent-type-design.rst
Labels: Pending committee review
