Repository ghc-proposals/ghc-proposals, pull requests merged in 2021-12, with the labels that each got.

#465 Add implementation tracking ticket to \cases
  proposals/0302-cases.rst
Labels: Non-proposal

#468 add link to accepted, unimplemented proposals
  README.rst
Labels: Non-proposal

#433 Unsatisfiable
  proposals/0000-unsatisfiable.rst
Labels: Needs revision

#460 371-non-magical-eq: more graceful migration (under review)
  proposals/0371-non-magical-eq.md
Labels: Pending shepherd recommendation
