Repository ghc-proposals/ghc-proposals, pull requests merged in 2023-06, with the labels that each got.

#594 Mark 3 proposals as implemented
  proposals/0540-jsem.rst
  proposals/0541-warning-pragmas-with-categories.rst
  proposals/0547-no-kind-equalities.rst
Labels: Non-proposal

#586 Split -Wunused-imports (under review)
  proposals/0000-split-wunused-imports.md
Labels: Accepted

#575 Deprecated instances (under review)
  proposals/0000-deprecated-instances.rst
Labels: Pending committee review
