Repository ghc-proposals/ghc-proposals, pull requests merged in 2024-01, with the labels that each got.

#613 GHC2024
  proposals/0000-ghc2024.rst
Labels: Pending committee review

#626 #281 Visible forall in types of terms: data constructors, patterns, polytypes, drop the binder restriction
  proposals/0281-visible-forall.rst
  proposals/0402-gadt-syntax.rst
Labels: Accepted

#493 Allow SPECIALISE to work with expressions
  proposals/0493-specialise-expressions.rst
Labels: Pending committee review

#633 Add table of contents to the README
  README.rst
Labels: Non-proposal

#569 Multiline string literals
  proposals/0569-multiline-strings.rst
Labels: Pending committee review
