Repository ghc-proposals/ghc-proposals, pull requests merged in 2024-08, with the labels that each got.

#637 Modify multiline string proposal to remove one trailing newline
  proposals/0569-multiline-strings.rst
Labels: Accepted

#652 Import shadowing (under review)
  proposals/0000-import-shadowing.rst
Labels: Accepted, Pending shepherd recommendation

#577 Amend the Higher Order Patterns proposal
  proposals/0555-template-patterns.rst
Labels: Amendment

#671 Rewrite build scripts to support non-Nix + autobuild
  .travis.yml
  Makefile
  README.rst
  build.sh
  venv.sh
Labels: Non-proposal

#660 Amend #366 to correct references to RecordDotSyntax
  proposals/0366-no-ambiguous-field-access.rst
Labels: Amendment
