Repository ghc-proposals/ghc-proposals, pull requests merged in 2025-08, with the labels that each got.

#705 Explicit Level Imports: refine specification for exports
  proposals/0682-explicit-level-imports.rst
Labels: Amendment

#669 Add categorization of language extensions
  proposals/0601-extension-lifecycle-framework.md
  proposals/0669-extension-categorization.md
Labels: Pending committee review

#717 Fix: Repair format in 522 Or patterns
  proposals/0522-or-patterns.rst
Labels: Non-proposal
